Style/AccessModifierDeclarations:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false